### ISSUE TITLE
quantumultx下出错

### ISSUE THREAD

**Issue by nasaboy** [missuo/ASN-China#1]
添加完规则后，更新资源，提示是Invalid Line IP-ASN,140731，试过把 //及后面的字符删除，只保留IP-ASN,140731，也还是一样有问题，但是我直接在配置文件里写入IP-ASN,140731，就不会报错，搞不懂是哪里的问题了。

**Comment by missuo** [comment]
注释不会影响使用。请您使用资源解析器。

~~~
# 资源解析器，自定义各类远程资源的转换
resource_parser_url=https://cdn.jsdelivr.net/gh/KOP-XIAO/QuantumultX@master/Scripts/resource-parser.js
~~~

**Comment by nasaboy** [comment]
感谢回复，按您说的方法已搞定。
